### ISSUE TITLE
Can't add the "Remove all role assignments" or a similar option (e.g. "Select/remove data role assignments" ) to the three-dotted menu of a report object

### ISSUE THREAD

**Issue by Stefan-Dimitrov-Stoyanov** [sassoftware/sas-viya-sdk-js#10]
Hi there,

We use SAS VA SDK 1.10.0 to embed a VA report created on SAS Viya 2022.1.2.

We need to enable the end-user of the web app to select/remove data role assignments from different report objects: e.g. list table, crosstab, line chart, waterfall chart.

In SAS Visual Analytics on SAS Viya, a guest user can use the "Remove all role assignments" from the three-dotted menu of the respective objects:
![image](https://user-images.githubusercontent.com/57138417/181263617-8a4c4bc6-cbbd-4718-8e01-f89a8873bf8e.png)
After removing all role assignments, the end user can add to the report object the data items they wish:
![image](https://user-images.githubusercontent.com/57138417/181264607-9ce0064a-6cd8-4d7e-80b8-3670c4b1181c.png)
For example, to a list table:
![image](https://user-images.githubusercontent.com/57138417/181264781-a6ebb7ab-de44-4e1d-929f-9bbd89b5acf7.png)
Or to a line chart:
![image](https://user-images.githubusercontent.com/57138417/181265089-3c9d127d-faa9-4d65-8bb4-17ad87981e2f.png)

However, we don't see this option available in the web app while using SAS Viya SDK.

Please, enable the "Remove all role assignmnets" option (or even better, a similar option, e.g. "Select/remove data role assignmnts) from the three-dotted menu of the respective objects in SAS Viya SDK. 

Thank you very much in advance!

**Comment by brmorr** [comment]
Hi @Stefan-Dimitrov-Stoyanov,

The SAS Visual Analytics behavior that you are referencing is part of its report editing capabilities.  This is intended to be done by report designers.  Once a report is created, it can then be opened and viewed in SAS Visual Analytics "view mode" or embedded with the SDK.  But the SDK is not meant to be a replacement for the SAS Visual Analytics application.  It is only meant to provide tools for embedding existing report objects, so that they can be viewed outside of the context of the full SAS Visual Analytics application.  It does not have report building capabilities, and that is not something is in the roadmap.  

That said, report viewers (as opposed to designers) do have capabilities in view mode that allow them to do some limited role replacement on objects.  This set of functions is controlled by the "viewer customizations" controls, as seen here.
![Screen Shot 2022-07-27 at 10 23 13 AM](https://user-images.githubusercontent.com/20012878/181275220-28007533-1c72-448c-a43b-0d597aaa0199.png)
The VA SDK does not currently support any viewer customization features, but it is something that is being discussed.  But for the near term your only editing options will be to use the SAS Visual Analytics application.

**Comment by Stefan-Dimitrov-Stoyanov** [comment]
Hi, @brmorr,

Thank you very much for the swift response. It is pretty comprehensive and clear.

To clarify, I don't refer to the report editing capabilities. My reference indeed is to the viewer customisation features. As I mentioned, a guest user (a guest user is not a report editor but only a report viewer) can use the "Remove all role assignments" from the three-dotted menu of the respective objects to remove/add any data items available to a report object. And this option is available when the report viewer customisation is set to "Data edits".

I am glad you discussed the VA SDK support of the viewer customisation features. The sooner this integration happens, the better for the SAS customers.

Best regards,
Stefan

**Comment by brmorr** [comment]
@Stefan-Dimitrov-Stoyanov,

Does your use case also require the support of "user state", such that viewers who make customizations can then reopen the report later and it will retain their changes?  The SDK currently doesn't support saving/restoring user state either, which I think seems like a prerequisite for supporting customization.  I'm curious to hear your view on this as it relates to your specific use case.

**Comment by Stefan-Dimitrov-Stoyanov** [comment]
Hi, @brmorr,

It is good that you raise the question about "user state" preservation. Indeed our use case requires saving/restoring a user state with the customisations done by the user. Then, we need the end-user of the app to be able to share a link with the customised user state of the app to be opened by another end-user(s).

Best Regards,
Stefan
