### ISSUE TITLE
Uncaught (in promise) TypeError that appears in Firefox only

### ISSUE THREAD

**Issue by YuryShkoda** [sassoftware/sas-viya-sdk-js#29]
There is an `Uncaught (in promise) TypeError` thrown error that appears in Firefox only.
It happens when a selection is made in DDC, but only in one DDC (there are other similar components that work totally fine).
The page also reloads (which probably happens because of `304` status for the first request).
OS: `macOS`
Firefox: `102.4.0`
SAS VA SDK: `1.13.0`
Console:
<img width="1813" alt="image" src="https://user-images.githubusercontent.com/25773492/199032852-555e8f35-da4b-4129-aa3f-853a288d6012.png">
Network:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/25773492/199034915-68e7421f-f194-433c-927c-fe4844e6809b.png">

**Comment by brmorr** [comment]
Does your DDC itself use the VASDK?  I ask because the network error seems to be happening in the vasdk authentication code, which would only be happening as the SDK is first loading, not when responding to a DDC.  Unless your DDC is using the VASDK.

Is it possible for you to narrow down the scenario to something that I could reproduce on our end?

**Comment by YuryShkoda** [comment]
@brmorr , I found the root cause of the issue and it is not related to the VASDK.
Thank you very much for your support and sorry for the false alarm. I'll close the issue.
